[package]
authors = ["Lars Francke <lars.francke@stackable.de>"]
description = "Stackable Operator for Trino"
edition = "2018"
license = "OSL-3.0"
name = "stackable-trino-operator-binary"
repository = "https://github.com/stackabletech/trino-operator"
version = "0.1.0-nightly"
build = "build.rs"

[dependencies]
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", branch = "main" }
stackable-trino-crd = { path = "../crd" }
stackable-trino-operator = { path = "../operator" }

clap = "2.33"
k8s-openapi = { version = "0.13", default-features = false, features = ["v1_22"] }
tokio = { version = "1.10", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"

[build-dependencies]
built = { version =  "0.5", features = ["chrono", "git2"] }
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", branch = "main" }
stackable-trino-crd = { path = "../crd" }

[package.metadata.deb]
name = "stackable-trino-operator"
maintainer-scripts = "../../packaging/debian/"
systemd-units = { enable = false, unit-name = "stackable-trino-operator" }
assets = [
    ["../../target/release/stackable-trino-operator", "opt/stackable/trino-operator/", "755"],
    ["../../deploy/crd/trinocluster.crd.yaml", "etc/stackable/trino-operator/crd/", "644"],
    ["../../deploy/crd/restart.crd.yaml", "etc/stackable/trino-operator/crd/", "644"],
    ["../../deploy/crd/start.crd.yaml", "etc/stackable/trino-operator/crd/", "644"],
    ["../../deploy/crd/stop.crd.yaml", "etc/stackable/trino-operator/crd/", "644"],
    ["../../deploy/config-spec/properties.yaml", "etc/stackable/trino-operator/config-spec/", "644"],
]

[[bin]]
name = "stackable-trino-operator"
path = "src/stackable-trino-operator.rs"
