[package]
authors = ["Stackable GmbH <info@stackable.de>"]
build = "build.rs"
description = "Stackable Operator for Trino"
edition = "2021"
license = "OSL-3.0"
name = "stackable-trino-operator"
repository = "https://github.com/stackabletech/trino-operator"
version = "0.5.0-nightly"

[dependencies]
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag = "0.22.0" }
stackable-trino-crd = { path = "../crd" }

anyhow = "1.0"
clap = "3.2"
futures = { version = "0.3", features = ["compat"] }
openssl = "0.10.41"
pin-project = "1.0"
semver = "1.0"
serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
snafu = "0.7"
strum = { version = "0.24", features = ["derive"] }
tokio = { version = "1.20", features = ["full"] }
tracing = "0.1"

[build-dependencies]
built = { version =  "0.5", features = ["chrono", "git2"] }
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag = "0.22.0" }
stackable-trino-crd = { path = "../crd" }
