---
apiVersion: v2
name: trino-operator
version: "23.4.0"
appVersion: "23.4.0"
description: The Stackable Operator for Trino
home: https://github.com/stackabletech/trino-operator
maintainers:
  - name: Stackable
    url: https://www.stackable.tech
