---
apiVersion: v1
data:
  properties.yaml: |
    ---
    version: 0.1.0
    spec:
      units:
        - unit: &unitNodeEnvironment
            name: "node_environment"
            regex: "^[a-z][a-z0-9_]*[a-z0-9]$"
            examples:
              - "a1_2_3b"
        - unit: &unitMemory
            name: "memory"
            regex: "(^\\p{N}+)(?:\\s*)((?:b|k|m|g|t|p|kb|mb|gb|tb|pb|B|K|M|G|T|P|KB|MB|GB|TB|PB)\\b$)"
            examples:
              - "1024b"
              - "1024kb"
              - "500m"
              - "1g"

    ###################################################################################################
    # node.properties
    ###################################################################################################
    properties:
      - property: &nodeEnvironment
          propertyNames:
            - name: "node.environment"
              kind:
                type: "file"
                file: "node.properties"
          datatype:
            type: "string"
            unit: *unitNodeEnvironment
          roles:
            - name: "coordinator"
              required: true
            - name: "worker"
              required: true
          asOfVersion: "0.0.0"

    ###################################################################################################
    # config.properties
    ###################################################################################################
      - property: &coordinator
          propertyNames:
            - name: "coordinator"
              kind:
                type: "file"
                file: "config.properties"
          datatype:
            type: "bool"
          defaultValues:
            - fromVersion: "0.0.0"
              value: "false"
          roles:
            - name: "coordinator"
              required: true
            - name: "worker"
              required: true
          asOfVersion: "0.0.0"

      - property: &nodeSchedulerIncludeCoordinator
          propertyNames:
            - name: "node-scheduler.include-coordinator"
              kind:
                type: "file"
                file: "config.properties"
          datatype:
            type: "bool"
          defaultValues:
            - fromVersion: "0.0.0"
              value: "false"
          roles:
            - name: "coordinator"
              required: true
          asOfVersion: "0.0.0"

      - property: &httpServerHttpPort
          propertyNames:
            - name: "http-server.http.port"
              kind:
                type: "file"
                file: "config.properties"
          datatype:
            type: "integer"
            min: "1024"
            max: "65535"
          defaultValues:
            - fromVersion: "0.0.0"
              value: "8080"
          roles:
            - name: "coordinator"
              required: false
            - name: "worker"
              required: false
          asOfVersion: "0.0.0"

      - property: &httpServerHttpsPort
          propertyNames:
            - name: "http-server.https.port"
              kind:
                type: "file"
                file: "config.properties"
          datatype:
            type: "integer"
            min: "1024"
            max: "65535"
          defaultValues:
            - fromVersion: "0.0.0"
              value: "8443"
          roles:
            - name: "coordinator"
              required: false
            - name: "worker"
              required: false
          asOfVersion: "0.0.0"

      - property: &queryMaxMemory
          propertyNames:
            - name: "query.max-memory"
              kind:
                type: "file"
                file: "config.properties"
          datatype:
            type: "string"
            unit: *unitMemory
          defaultValues:
            - fromVersion: "0.0.0"
              value: "50GB"
          roles:
            - name: "coordinator"
              required: true
            - name: "worker"
              required: true
          asOfVersion: "0.0.0"

      - property: &queryMaxMemoryPerNode
          propertyNames:
            - name: "query.max-memory-per-node"
              kind:
                type: "file"
                file: "config.properties"
          datatype:
            type: "string"
            unit: *unitMemory
          defaultValues:
            - fromVersion: "0.0.0"
              value: "1GB"
          roles:
            - name: "coordinator"
              required: true
            - name: "worker"
              required: true
          asOfVersion: "0.0.0"

      - property: &httpServerAuthenticationType
          propertyNames:
            - name: "http-server.authentication.type"
              kind:
                type: "file"
                file: "config.properties"
          datatype:
            type: "string"
          roles:
            - name: "coordinator"
              required: false
          asOfVersion: "0.0.0"

    ###################################################################################################
    # password-authenticator.properties
    ###################################################################################################

      - property: &passwordAuthenticatorName
          propertyNames:
            - name: "password-authenticator.name"
              kind:
                type: "file"
                file: "password-authenticator.properties"
          datatype:
            type: "string"
          allowedValues:
            - "file"
            - "ldap"
          roles:
            - name: "coordinator"
              required: false
          asOfVersion: "0.0.0"

      - property: &passwordAuthenticatorName
          propertyNames:
            - name: "file.password-file"
              kind:
                type: "file"
                file: "password-authenticator.properties"
          datatype:
            type: "string"
          roles:
            - name: "coordinator"
              required: false
          asOfVersion: "0.0.0"


    ###################################################################################################
    # jvm.config
    ###################################################################################################

    ###################################################################################################
    # log.properties
    ###################################################################################################

      - property: &ioTrino
          propertyNames:
            - name: "io.trino"
              kind:
                type: "file"
                file: "log.properties"
          datatype:
            type: "string"
          defaultValues:
            - fromVersion: "0.0.0"
              value: "INFO"
          allowedValues:
            - "INFO"
            - "DEBUG"
            - "WARN"
            - "ERROR"
          roles:
            - name: "coordinator"
              required: true
            - name: "worker"
              required: true
          asOfVersion: "0.0.0"
kind: ConfigMap
metadata:
  name: trino-operator-configmap
  labels:
    app.kubernetes.io/name: trino-operator
    app.kubernetes.io/instance: trino-operator
    app.kubernetes.io/version: "23.4.0"
